### ISSUE TITLE
canvasによる背景白のボックスが表示される

### ISSUE THREAD

**Issue by wakkihaya** [Arpedia/enPiT-Funbrella#42]
## バグ内容
各versionのhtmlの上に、gameApp.jsで生成されたcanvas が上に重なってしまう。
canvasの背景色が白なので、白のボックスが表示されている。

## 発生環境・操作
- sunny.htmlなどを表示。
- F12キーでデベロッパーツールを開くと、canvas タグが生成され、marginやheightが自動的に設定されている事がわかる。

## 期待される動作
パターンとしては、2つある。
1. canvasの背景色を透過させて、htmlの画面を写す。
2. ドメインから天気を取ってきて、canvas内の背景をjs内で変えてしまう。

**Comment by Arpedia** [comment]
#65 で解決
